### PR TITLE
Revise Repository

### PR DESCRIPTION
**Pull request by w2sv**
I did I a general revision of the repository to make the program more usable & the repository more maintainable. The changes I made include:

- the splitting of the script into several files residing in the newly created `src` dir
- code polishing
- addition of argparse to make passing of configuration arguments upon program execution feasible
- automatic retrieval of a connected external keyboard / possibility to select one in case of multiple being connected 
- corresponding adjustment of the README, as well as addition of instructions as to how to enable the program in conjunction with a specific python environment, as the provided instructions did not shed light on that, leading to me having to research that myself to get it to run on my machine
- formatting, updating & addition of my name (if that's cool with you) to the LICENSE

### CODE REVIEW

**Comment by finkrer** [comment]
Hi @w2sv. Thank you for your contribution and for the time spent improving my project.

Two points I need to address:

1. As for the license, I'm glad that you figured out that you can't just remove my name (😂), since that is directly against the license terms. I don't mind you adding your name there, but as far as I understand, it is supposed to go (exactly) like this: `Copyright 2020 Evgeny Zyrianov (finkrer), 2023 Janek Zangenberg (w2sv)`.
2. In terms of everything else, the changes look fine to me, but unfortunately I have no way to test them, since I haven't been using Linux for a couple of years now. It seems to me that including significant changes just like that, with no way to test the resulting code or fix any bugs that may be discovered later, is not a good idea.

So, I have this proposal: I can make you a collaborator and basically a maintainer of the repo. You will be free to do whatever you want, but if there's an issue with your code, you will have to sort it out. You can see that there's an open issue already, fixing that would be great as well. Other than that, there's basically nothing going on here, so it's not a huge commitment.

**Comment by w2sv** [comment]
Alright, you can make me a contributor and I'll do my best maintaining the repo and fixing potential issues. 

I wasn't aware of the name order thing regarding the license, but makes totally sense to first name the original creator of the repository.

**Comment by w2sv** [comment]
I've updated the pr respectively.

**Comment by finkrer** [comment]
Okay, thank you. I will now send you the invite. You can accept your own pull request.

**Pull request merged**
